version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "1"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y unzip jq yum-utils shadow-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform -version

  pre_build:
    commands:
      - echo "Listing files in working directory for verification..."
      - ls -la
      - echo "Initializing Terraform..."
      - terraform init -input=false

  build:
    commands:
      - echo "Validating Terraform configuration..."
      - terraform validate
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan -input=false
      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
